from __future__ import annotations

import asyncio
import hashlib
import json
import subprocess
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from booxdrop_cli import (
    DEFAULT_PDF_CACHE_DIR,
    _ensure_pdf_cached,
    _record_enrichment_to_db,
    _resolve_pdf_path,
    extract_markdown_from_pdf,
    latex_escape,
    load_manifest,
    normalize_arxiv_id,
    prime_cache,
    slugify,
    summarize_category_section,
    summarize_paper_entry,
    summary_index_path,
    traverse_references,
)


GENERATED_HEADER = "%% Auto-generated by arxiv-radar periodical"
DEFAULT_PERIODICAL_QUEUE_PATH = "artifacts/periodical-queue.json"


def _entry_id(entry: dict[str, Any]) -> str:
    return str(entry.get("resolved_id") or entry.get("arxiv_id") or "")


def _published_key(entry: dict[str, Any]) -> str:
    return str(entry.get("published") or entry.get("updated") or "")


def select_focus_entry(
    entries: list[dict[str, Any]],
    focus: str | None = None,
) -> dict[str, Any] | None:
    if not entries:
        return None
    if focus:
        needle = focus.lower()
        for entry in entries:
            ids = {
                str(entry.get("arxiv_id") or "").lower(),
                str(entry.get("resolved_id") or "").lower(),
            }
            title = str(entry.get("title") or "").lower()
            if any(needle in item_id for item_id in ids) or needle in title:
                return entry
        raise ValueError(f"focal paper not found in manifest: {focus}")
    return sorted(
        entries,
        key=lambda entry: (
            int(entry.get("citation_count") or 0),
            _published_key(entry),
            str(entry.get("title") or ""),
        ),
        reverse=True,
    )[0]


def select_supporting_entries(
    entries: list[dict[str, Any]],
    focus_entry: dict[str, Any] | None,
    supporting_papers: int,
) -> list[dict[str, Any]]:
    if supporting_papers < 0:
        raise ValueError("supporting_papers must be non-negative")
    focus_id = _entry_id(focus_entry or {})
    candidates = [entry for entry in entries if _entry_id(entry) != focus_id]
    focus_category = str((focus_entry or {}).get("category") or "")
    return sorted(
        candidates,
        key=lambda entry: (
            str(entry.get("category") or "") == focus_category,
            int(entry.get("citation_count") or 0),
            _published_key(entry),
            str(entry.get("title") or ""),
        ),
        reverse=True,
    )[:supporting_papers]


def select_entries_by_ids(
    entries: list[dict[str, Any]],
    ids: list[str],
) -> list[dict[str, Any]]:
    by_id = {_entry_id(entry): entry for entry in entries}
    by_arxiv_id = {str(entry.get("arxiv_id") or ""): entry for entry in entries}
    selected = []
    for item_id in ids:
        entry = by_id.get(item_id) or by_arxiv_id.get(item_id)
        if entry is not None and entry not in selected:
            selected.append(entry)
    return selected


def _topic_title(entry: dict[str, Any]) -> str:
    area = str(entry.get("category") or "Research")
    title = str(entry.get("title") or "Untitled")
    return f"{area}: {title}"


def _paper_ref(entry: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": _entry_id(entry),
        "arxiv_id": str(entry.get("arxiv_id") or ""),
        "title": str(entry.get("title") or "Untitled"),
        "category": str(entry.get("category") or "Uncategorized"),
        "citation_count": int(entry.get("citation_count") or 0),
        "published": str(entry.get("published") or ""),
    }


def propose_periodical_topics(
    manifest_path: str,
    *,
    limit: int = 8,
    supporting_papers: int = 6,
) -> list[dict[str, Any]]:
    manifest = load_manifest(manifest_path)
    entries = [entry for entry in manifest.get("entries", []) if isinstance(entry, dict)]
    ranked = sorted(
        entries,
        key=lambda entry: (
            int(entry.get("citation_count") or 0),
            _published_key(entry),
            str(entry.get("title") or ""),
        ),
        reverse=True,
    )
    topics = []
    for entry in ranked[:limit]:
        support = select_supporting_entries(entries, entry, supporting_papers)
        topic_id = slugify(_entry_id(entry) or str(entry.get("title") or "topic"))
        topics.append(
            {
                "id": topic_id,
                "title": _topic_title(entry),
                "status": "proposed",
                "focus": _entry_id(entry),
                "focus_paper": _paper_ref(entry),
                "supporting_papers": [_paper_ref(item) for item in support],
                "rationale": str(entry.get("summary") or "")[:500],
            }
        )
    return topics


def load_periodical_queue(queue_path: str = DEFAULT_PERIODICAL_QUEUE_PATH) -> dict[str, Any]:
    path = Path(queue_path)
    if not path.exists():
        return {"version": 1, "topics": []}
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"periodical queue must be an object: {queue_path}")
    payload.setdefault("version", 1)
    payload.setdefault("topics", [])
    return payload


def write_periodical_queue(
    queue: dict[str, Any],
    queue_path: str = DEFAULT_PERIODICAL_QUEUE_PATH,
) -> None:
    path = Path(queue_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(queue, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def add_periodical_queue_item(
    *,
    manifest_path: str,
    queue_path: str = DEFAULT_PERIODICAL_QUEUE_PATH,
    focus: str,
    title: str | None = None,
    series: str = "Research Radar",
    issue: int | None = None,
    supporting_papers: int = 6,
) -> dict[str, Any]:
    manifest = load_manifest(manifest_path)
    entries = [entry for entry in manifest.get("entries", []) if isinstance(entry, dict)]
    focus_entry = select_focus_entry(entries, focus)
    if focus_entry is None:
        raise ValueError("cannot queue a topic from an empty manifest")
    support = select_supporting_entries(entries, focus_entry, supporting_papers)
    item = {
        "id": slugify(f"{issue or 'next'}-{_entry_id(focus_entry)}"),
        "status": "queued",
        "series": series,
        "issue": issue,
        "title": title or _topic_title(focus_entry),
        "focus": _entry_id(focus_entry),
        "focus_paper": _paper_ref(focus_entry),
        "supporting_papers": [_paper_ref(entry) for entry in support],
        "created_at": datetime.now(UTC).isoformat(),
        "manifest_path": manifest_path,
    }
    queue = load_periodical_queue(queue_path)
    topics = [topic for topic in queue.get("topics", []) if topic.get("id") != item["id"]]
    topics.append(item)
    queue["topics"] = topics
    write_periodical_queue(queue, queue_path)
    return item


def get_periodical_queue_item(
    queue_item: str,
    queue_path: str = DEFAULT_PERIODICAL_QUEUE_PATH,
) -> dict[str, Any]:
    queue = load_periodical_queue(queue_path)
    for item in queue.get("topics", []):
        if item.get("id") == queue_item:
            return item
    raise ValueError(f"periodical queue item not found: {queue_item}")


def _paper_chapter_filename(entry: dict[str, Any]) -> str:
    arxiv_id = slugify(str(entry.get("resolved_id") or entry.get("arxiv_id", "unknown")))
    return f"{arxiv_id}.tex"


def _generated_tex(path: Path, body: str) -> None:
    path.write_text(f"{GENERATED_HEADER}\n{body}", encoding="utf-8")


def _clear_generated_tex(chapters_dir: Path) -> None:
    chapters_dir.mkdir(parents=True, exist_ok=True)
    for path in chapters_dir.glob("*.tex"):
        path.unlink()


def render_paper_chapter(
    entry: dict[str, Any],
    summary: dict[str, Any],
    foundational_refs: list[dict[str, Any]] | None = None,
) -> str:
    title = latex_escape(str(entry.get("title", "Untitled")))
    arxiv_id = str(entry.get("arxiv_id", ""))
    citations = int(entry.get("citation_count") or 0)
    published = str(entry.get("published", ""))[:10]
    authors = ", ".join((entry.get("authors") or [])[:3])
    if len(entry.get("authors") or []) > 3:
        authors += " et al."
    area = latex_escape(str(summary.get("area_of_progress", "")))
    confidence = str(summary.get("confidence", "unknown")).upper()
    results = latex_escape(str(summary.get("results_summary", "")))
    framing = latex_escape(str(summary.get("intake_framing", "")))
    citation_signal = latex_escape(str(summary.get("citation_signal", "")))
    abs_url = str(entry.get("abs_url", ""))

    lines = [
        r"\section*{" + f"{title}" + "}",
        r"\addcontentsline{toc}{section}{" + f"{title}" + "}",
        "",
        r"\papermeta{",
        rf"\textbf{{{latex_escape(authors)}}} \quad | \quad {published} \quad | \quad {citations} citations \quad | \quad arXiv:{latex_escape(arxiv_id)}",
        r"}",
        "",
    ]
    if area:
        lines.append(rf"\areabox{{{area}}}\quad ")
    lines.append(rf"\confidencebadge{{{confidence}}}")
    lines.append("")

    lines.extend(
        [
            r"\papercard{",
            rf"\insightbox{{{results}}}",
            r"\vspace{0.3em}",
            rf"\textbf{{Why it matters:}} {framing}",
            r"}",
            "",
        ]
    )

    if citation_signal:
        lines.extend(
            [
                r"\noindent\textbf{\color{mediumgray}Citation signal:} ",
                rf"{citation_signal}",
                "",
            ]
        )

    claims = summary.get("primary_claims", [])
    if claims:
        lines.append(r"\noindent\textbf{\color{darkgray}Key Claims}")
        lines.append(r"\begin{itemize}")
        for claim in claims[:5]:
            lines.append(rf"\item {latex_escape(str(claim))}")
        lines.extend([r"\end{itemize}", ""])

    bg = summary.get("required_background", [])
    if bg:
        lines.append(r"\noindent\textbf{\color{mediumgray}Background Needed}")
        lines.append(r"\begin{itemize}")
        for item_text in bg[:4]:
            lines.append(rf"\item {latex_escape(str(item_text))}")
        lines.extend([r"\end{itemize}", ""])

    oq = summary.get("open_questions", [])
    if oq:
        lines.append(r"\noindent\textbf{\color{mediumgray}Open Questions}")
        lines.append(r"\begin{itemize}")
        for item_text in oq[:3]:
            lines.append(rf"\item {latex_escape(str(item_text))}")
        lines.extend([r"\end{itemize}", ""])

    if foundational_refs:
        lines.extend(
            [
                r"\noindent\textbf{\color{mediumgray}Foundational References}",
                r"\begin{itemize}",
            ]
        )
        for ref in foundational_refs[:6]:
            ref_title = latex_escape(str(ref.get("title", "Unknown")))
            ref_year = ref.get("publication_year", "")
            ref_cites = int(ref.get("citation_count") or 0)
            lines.append(rf"\item {ref_title} ({ref_year}, {ref_cites} citations)")
        lines.extend([r"\end{itemize}", ""])

    lines.extend(
        [
            r"\noindent{\footnotesize",
            rf"\textcolor{{accentblue}}{{\url{{{abs_url}}}}}",
            r"}",
            r"\medskip",
            "",
        ]
    )
    return "\n".join(lines) + "\n"


def render_executive_summary_chapter(
    sections: list[dict[str, Any]],
    category_summaries: dict[str, dict[str, Any]],
    manifest: dict[str, Any],
    *,
    series: str,
    issue: int | None,
    focus_section: dict[str, Any] | None,
    supporting_sections: list[dict[str, Any]],
) -> str:
    category_counts: dict[str, int] = {}
    for item in sections:
        cat = str(item["entry"].get("category") or "Uncategorized")
        category_counts[cat] = category_counts.get(cat, 0) + 1

    top_cited = sorted(
        sections,
        key=lambda item: int(item["entry"].get("citation_count") or 0),
        reverse=True,
    )[:5]

    generated_at = str(manifest.get("generated_at") or "")
    issue_label = f"Issue {issue}" if issue is not None else "Unnumbered Issue"
    lines = [
        r"\section*{In This Issue}",
        r"\addcontentsline{toc}{section}{In This Issue}",
        "",
        rf"\textbf{{{latex_escape(series)} {latex_escape(issue_label)}}}",
        "",
        rf"This issue builds a durable reading path around {len(sections)} selected papers across {len(category_counts)} categories.",
        "",
    ]
    if generated_at:
        lines.extend([rf"\textit{{Radar generated: {latex_escape(generated_at)}}}", ""])

    if focus_section:
        entry = focus_section["entry"]
        summary = focus_section["summary"]
        lines.extend(
            [
                r"\section*{Through Line}",
                r"\addcontentsline{toc}{section}{Through Line}",
                "",
                rf"The focal paper is \textbf{{{latex_escape(str(entry.get('title', 'Untitled')))}}}.",
                "",
                latex_escape(str(summary.get("intake_framing") or summary.get("results_summary") or "")),
                "",
            ]
        )
        supporting_titles = [
            latex_escape(str(item["entry"].get("title", "Untitled")))
            for item in supporting_sections
        ]
        if supporting_titles:
            lines.extend(
                [
                    r"\noindent\textbf{\color{mediumgray}Supporting Arc}",
                    r"\begin{itemize}",
                ]
            )
            for title in supporting_titles:
                lines.append(rf"\item {title}")
            lines.extend([r"\end{itemize}", ""])

    if top_cited:
        lines.extend(
            [
                r"\noindent\textbf{\color{darkgray}Highest Citation Signal}",
                r"\begin{itemize}",
            ]
        )
        for item in top_cited:
            entry = item["entry"]
            title = latex_escape(str(entry.get("title", "Untitled")))
            cites = int(entry.get("citation_count") or 0)
            lines.append(rf"\item {title} ({cites} citations)")
        lines.extend([r"\end{itemize}", ""])

    for category, cat_summary in sorted(category_summaries.items()):
        lines.extend(
            [
                rf"\section*{{{latex_escape(category)} Overview}}",
                rf"\addcontentsline{{toc}}{{section}}{{{latex_escape(category)} Overview}}",
                "",
                latex_escape(str(cat_summary.get("executive_summary", ""))),
                "",
            ]
        )
        themes = cat_summary.get("shared_themes", [])
        if themes:
            lines.append(r"\noindent\textbf{\color{mediumgray}Themes}")
            lines.append(r"\begin{itemize}")
            for theme in themes[:4]:
                lines.append(rf"\item {latex_escape(str(theme))}")
            lines.extend([r"\end{itemize}", ""])
        priorities = cat_summary.get("intake_priorities", [])
        if priorities:
            lines.append(r"\noindent\textbf{\color{mediumgray}Reading Order}")
            lines.append(r"\begin{itemize}")
            for priority in priorities[:4]:
                lines.append(rf"\item {latex_escape(str(priority))}")
            lines.extend([r"\end{itemize}", ""])

    return "\n".join(lines) + "\n"


def render_bibliography_chapter(
    sections: list[dict[str, Any]],
    foundational_sections: list[dict[str, Any]] | None = None,
) -> str:
    lines = [
        r"\section*{Bibliography}",
        r"\addcontentsline{toc}{section}{Bibliography}",
        "",
    ]
    grouped: dict[str, list[dict[str, Any]]] = {}
    for item in sections:
        cat = str(item["entry"].get("category") or "Uncategorized")
        grouped.setdefault(cat, []).append(item)
    for category, items in sorted(grouped.items()):
        lines.extend([rf"\section{{{latex_escape(category)}}}", r"\begin{itemize}"])
        for item in items:
            entry = item["entry"]
            title = latex_escape(str(entry.get("title", "Untitled")))
            arxiv_id = latex_escape(str(entry.get("arxiv_id", "")))
            url = str(entry.get("abs_url", ""))
            lines.append(rf"\item {title}. arXiv {arxiv_id}. \url{{{url}}}")
        lines.extend([r"\end{itemize}", ""])
    if foundational_sections:
        lines.extend([r"\section{Foundational References}", r"\begin{itemize}"])
        for item in foundational_sections:
            entry = item["entry"]
            title = latex_escape(str(entry.get("title", "Untitled")))
            cites = int(entry.get("citation_count") or 0)
            year = entry.get("publication_year", "")
            url = str(entry.get("abs_url", ""))
            lines.append(rf"\item {title} ({year}, {cites} citations). \url{{{url}}}")
        lines.extend([r"\end{itemize}", ""])
    return "\n".join(lines) + "\n"


def render_foundational_chapter(foundational_sections: list[dict[str, Any]]) -> str:
    lines = [
        r"\section*{Foundational References}",
        r"\addcontentsline{toc}{section}{Foundational References}",
        "",
        r"These foundational papers were discovered through citation traversal of the primary radar selections. "
        r"Each paper received a full intake summary to help build foundational knowledge.",
        "",
    ]
    for item in foundational_sections:
        entry = item["entry"]
        summary = item["summary"]
        title = latex_escape(str(entry.get("title", "Untitled")))
        citations = int(entry.get("citation_count") or 0)
        year = entry.get("publication_year", "")
        abs_url = str(entry.get("abs_url", ""))
        results = latex_escape(str(summary.get("results_summary", "")))
        area = latex_escape(str(summary.get("area_of_progress", "")))
        confidence = str(summary.get("confidence", "unknown")).upper()
        lines.extend(
            [
                r"\section*{" + f"{title}" + "}",
                rf"\noindent\textbf{{Year:}} {year}\quad \textbf{{Citations:}} {citations}\quad \textbf{{Confidence:}} [{confidence}]",
                "",
                rf"\textit{{{area}}}" if area else "",
                results,
                "",
            ]
        )
        for key, label in [
            ("primary_claims", "Primary Claims"),
            ("required_background", "Required Background"),
            ("long_range_insights", "Long-Range Insights"),
            ("modern_connections", "Modern Connections"),
        ]:
            values = summary.get(key)
            if values:
                lines.extend([rf"\noindent\textbf{{{label}:}}", r"\begin{itemize}"])
                for value in values:
                    lines.append(rf"\item {latex_escape(str(value))}")
                lines.extend([r"\end{itemize}", ""])
        if abs_url:
            lines.extend([rf"\noindent\url{{{abs_url}}}", ""])
        lines.extend([r"\medskip", ""])
    return "\n".join(lines) + "\n"


def render_periodical_main_tex(
    *,
    title: str,
    series: str,
    issue: int | None,
    focus_title: str | None,
    chapter_includes: list[str],
) -> str:
    includes = "\n".join(rf"\include{{chapters/{name}}}" for name in chapter_includes)
    issue_label = f"Issue {issue}" if issue is not None else "Unnumbered Issue"
    display_title = focus_title or title
    return (
        r"%% Research Radar Periodical"
        "\n"
        r"%% Auto-generated -- do not edit directly"
        "\n"
        r"\documentclass{research-radar}"
        "\n\n"
        rf"\reporttitle{{{latex_escape(series)} {latex_escape(issue_label)}}}"
        "\n"
        r"\reportstatus{Draft}"
        "\n"
        rf"\issueinfo{{{latex_escape(issue_label)} -- \today}}"
        "\n\n"
        r"\begin{document}"
        "\n\n"
        r"\thispagestyle{cover}"
        "\n\n"
        r"\begin{tikzpicture}[remember picture,overlay]"
        "\n"
        r"  \fill[coverbg] (current page.north west) rectangle (current page.south east);"
        "\n"
        r"  \node[anchor=north west, text width=0.85\paperwidth, inner sep=0pt]"
        "\n"
        r"    at ([shift={(0.6in,-0.8in)}]current page.north west) {"
        "\n"
        r"      {\color{coveraccent}\Large\bfseries\MakeUppercase{Research Radar}}"
        "\n"
        r"      \\[0.6em]"
        r"      {\color{white}\rule{4cm}{0.6pt}}"
        "\n"
        r"      \\[0.8em]"
        rf"      {{\color{{white}}\huge\bfseries {latex_escape(display_title)}}}"
        "\n"
        r"      \\[1.2em]"
        rf"      {{\color{{white!70}}\large {latex_escape(series)} {latex_escape(issue_label)}}}"
        "\n"
        r"      \\[0.3em]"
        r"      {\color{white!50}\normalsize \today}"
        "\n"
        r"    };"
        "\n"
        r"\end{tikzpicture}"
        "\n\n"
        r"\vspace{6in}"
        "\n"
        r"\newpage"
        "\n\n"
        r"\thispagestyle{plain}"
        "\n"
        r"\tableofcontents"
        "\n"
        r"\newpage"
        "\n\n"
        f"{includes}\n\n"
        r"\appendix"
        "\n"
        r"\include{chapters/bibliography}"
        "\n\n"
        r"\end{document}"
        "\n"
    )


def write_periodical_project(
    *,
    periodical_dir: str,
    title: str,
    series: str,
    issue: int | None,
    manifest: dict[str, Any],
    manifest_path: str,
    manifest_sha256: str,
    sections: list[dict[str, Any]],
    focus_section: dict[str, Any] | None,
    supporting_sections: list[dict[str, Any]],
    category_summaries: dict[str, dict[str, Any]],
    foundational_sections: list[dict[str, Any]],
    ref_map: dict[str, list[dict[str, Any]]],
    model: str,
    variant: str | None,
    prompt_version: int,
    reference_depth: int,
) -> dict[str, Any]:
    periodical_path = Path(periodical_dir)
    chapters_dir = periodical_path / "chapters"
    periodical_path.mkdir(parents=True, exist_ok=True)
    _clear_generated_tex(chapters_dir)

    _generated_tex(
        chapters_dir / "executive-summary.tex",
        render_executive_summary_chapter(
            sections,
            category_summaries,
            manifest,
            series=series,
            issue=issue,
            focus_section=focus_section,
            supporting_sections=supporting_sections,
        ),
    )
    _generated_tex(
        chapters_dir / "bibliography.tex",
        render_bibliography_chapter(sections, foundational_sections),
    )

    chapter_includes = ["executive-summary"]
    if focus_section:
        focus_filename = _paper_chapter_filename(focus_section["entry"])
        _generated_tex(
            chapters_dir / focus_filename,
            render_paper_chapter(
                focus_section["entry"],
                focus_section["summary"],
                ref_map.get(_entry_id(focus_section["entry"]), []),
            ),
        )
        _generated_tex(
            chapters_dir / "focal-paper.tex",
            "\n".join(
                [
                    r"\section{Focal Paper}",
                    rf"\input{{chapters/{focus_filename.replace('.tex', '')}}}",
                    "",
                ]
            ),
        )
        chapter_includes.append("focal-paper")

    if supporting_sections:
        support_lines = [r"\section{Supporting Context}", ""]
        for item in supporting_sections:
            filename = _paper_chapter_filename(item["entry"])
            _generated_tex(
                chapters_dir / filename,
                render_paper_chapter(
                    item["entry"],
                    item["summary"],
                    ref_map.get(_entry_id(item["entry"]), []),
                ),
            )
            support_lines.append(rf"\input{{chapters/{filename.replace('.tex', '')}}}")
        _generated_tex(
            chapters_dir / "supporting-context.tex",
            "\n".join(support_lines) + "\n",
        )
        chapter_includes.append("supporting-context")

    context_ids = {_entry_id(item["entry"]) for item in [*(supporting_sections or [])]}
    if focus_section:
        context_ids.add(_entry_id(focus_section["entry"]))
    grouped_sections: dict[str, list[dict[str, Any]]] = {}
    for item in sections:
        if _entry_id(item["entry"]) in context_ids:
            continue
        cat = str(item["entry"].get("category") or "Uncategorized")
        grouped_sections.setdefault(cat, []).append(item)

    for category, items in sorted(grouped_sections.items()):
        category_slug = slugify(category)
        chapter_includes.append(category_slug)
        cat_lines = [rf"\section{{{latex_escape(category)}}}", ""]
        for item in items:
            entry = item["entry"]
            filename = _paper_chapter_filename(entry)
            arxiv_id = str(entry.get("resolved_id") or entry.get("arxiv_id", ""))
            paper_refs = ref_map.get(arxiv_id, [])
            _generated_tex(
                chapters_dir / filename,
                render_paper_chapter(entry, item["summary"], paper_refs),
            )
            cat_lines.append(rf"\input{{chapters/{filename.replace('.tex', '')}}}")
        _generated_tex(chapters_dir / f"{category_slug}.tex", "\n".join(cat_lines) + "\n")

    if foundational_sections:
        chapter_includes.append("foundational-references")
        _generated_tex(
            chapters_dir / "foundational-references.tex",
            render_foundational_chapter(foundational_sections),
        )

    main_tex_path = periodical_path / "research-radar.tex"
    main_tex_path.write_text(
        render_periodical_main_tex(
            title=title,
            series=series,
            issue=issue,
            focus_title=str(focus_section["entry"].get("title", "")) if focus_section else None,
            chapter_includes=chapter_includes,
        ),
        encoding="utf-8",
    )

    metadata = {
        "generated_at": datetime.now(UTC).isoformat(),
        "manifest_path": manifest_path,
        "manifest_sha256": manifest_sha256,
        "series": series,
        "issue": issue,
        "focus": _entry_id(focus_section["entry"]) if focus_section else None,
        "focus_title": str(focus_section["entry"].get("title", "")) if focus_section else None,
        "supporting_paper_count": len(supporting_sections),
        "supporting_papers": [_entry_id(item["entry"]) for item in supporting_sections],
        "paper_count": len(sections),
        "foundational_count": len(foundational_sections),
        "chapter_count": len(chapter_includes),
        "model": model,
        "variant": variant,
        "prompt_version": prompt_version,
        "reference_depth": reference_depth,
        "tex_class": "research-radar",
        "main_tex": str(main_tex_path),
    }
    (periodical_path / "build-metadata.json").write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return metadata


async def build_periodical(
    manifest_path: str,
    *,
    cache_dir: str = DEFAULT_PDF_CACHE_DIR,
    model: str,
    variant: str | None,
    summary_cache_dir: str,
    markdown_cache_dir: str,
    prompt_version: int,
    title: str,
    max_papers: int | None,
    periodical_dir: str = "tex/research-radar",
    series: str = "Research Radar",
    issue: int | None = None,
    focus: str | None = None,
    supporting_papers: int = 6,
    supporting_focuses: list[str] | None = None,
    refresh_summaries: bool = False,
    reference_depth: int = 2,
    max_references_per_paper: int = 10,
    min_reference_citations: int = 50,
    db_path: str | None = None,
) -> dict[str, Any]:
    if max_papers is not None and max_papers < 0:
        raise ValueError("max_papers must be non-negative")
    if reference_depth < 0:
        raise ValueError("reference_depth must be non-negative")
    if max_references_per_paper < 0:
        raise ValueError("max_references_per_paper must be non-negative")
    if supporting_papers < 0:
        raise ValueError("supporting_papers must be non-negative")

    build_id = None
    if db_path:
        from radar_db import get_db, init_db, start_periodical_build

        init_db(db_path)

    await prime_cache(manifest_path, cache_dir)
    manifest = load_manifest(manifest_path)
    entries = [entry for entry in manifest.get("entries", []) if isinstance(entry, dict)]
    if max_papers is not None:
        entries = entries[:max_papers]
    focus_entry = select_focus_entry(entries, focus)
    if supporting_focuses:
        supporting_entries = select_entries_by_ids(entries, supporting_focuses)
    else:
        supporting_entries = select_supporting_entries(entries, focus_entry, supporting_papers)
    issue_entries: list[dict[str, Any]] = []
    seen_issue_ids: set[str] = set()
    for entry in [focus_entry, *supporting_entries]:
        if entry is None:
            continue
        entry_id = _entry_id(entry)
        if entry_id in seen_issue_ids:
            continue
        issue_entries.append(entry)
        seen_issue_ids.add(entry_id)

    manifest_sha256 = hashlib.sha256(Path(manifest_path).read_bytes()).hexdigest()

    if db_path:
        from radar_db import entry_to_paper, record_periodical_paper, upsert_paper

        with get_db(db_path) as conn:
            build_id = start_periodical_build(
                conn,
                paper_count=len(issue_entries),
                reference_depth=reference_depth,
                model=model,
                manifest_sha256=manifest_sha256,
            )
            for entry in issue_entries:
                try:
                    upsert_paper(conn, entry_to_paper(entry, discovered_via="periodical"))
                except Exception:
                    pass
                record_periodical_paper(conn, build_id, str(entry.get("arxiv_id", "")), "primary")

    sections = []
    for entry in issue_entries:
        summary = await summarize_paper_entry(
            entry,
            cache_dir=cache_dir,
            summary_cache_dir=summary_cache_dir,
            markdown_cache_dir=markdown_cache_dir,
            model=model,
            variant=variant,
            prompt_version=prompt_version,
            refresh=refresh_summaries,
            db_path=db_path,
        )
        sections.append({"entry": entry, "summary": summary})
        if db_path:
            _record_enrichment_to_db(
                db_path,
                entry,
                summary,
                model,
                variant,
                prompt_version,
                "llm_summary",
            )

    grouped: dict[str, list[dict[str, Any]]] = {}
    for item in sections:
        grouped.setdefault(str(item["entry"].get("category") or "Uncategorized"), []).append(item)
    category_summaries = {}
    for category, items in grouped.items():
        category_summaries[category] = await summarize_category_section(
            category,
            items,
            summary_cache_dir=summary_cache_dir,
            model=model,
            variant=variant,
            prompt_version=prompt_version,
            refresh=refresh_summaries,
        )
    sections_by_id = {_entry_id(item["entry"]): item for item in sections}
    focus_section = (
        sections_by_id.get(_entry_id(focus_entry)) if focus_entry is not None else None
    )
    supporting_sections = [
        sections_by_id[_entry_id(entry)]
        for entry in supporting_entries
        if _entry_id(entry) in sections_by_id
    ]

    ref_map: dict[str, list[dict[str, Any]]] = {}
    foundational_sections: list[dict[str, Any]] = []
    if reference_depth > 0:
        ref_map = await asyncio.to_thread(
            traverse_references,
            issue_entries,
            max_depth=reference_depth,
            max_refs_per_paper=max_references_per_paper,
            min_citations=min_reference_citations,
        )
        unique_foundational: dict[str, dict[str, Any]] = {}
        for refs in ref_map.values():
            for ref in refs:
                key = ref.get("openalex_id") or ref.get("arxiv_id")
                if key and key not in unique_foundational:
                    unique_foundational[key] = ref
        if db_path:
            from radar_db import entry_to_paper, get_db, record_reference_edges, upsert_paper

            with get_db(db_path) as conn:
                for fref in unique_foundational.values():
                    if fref.get("arxiv_id") and fref["arxiv_id"].startswith(("1", "2")):
                        try:
                            upsert_paper(
                                conn,
                                entry_to_paper(fref, discovered_via="reference_traversal"),
                            )
                        except Exception:
                            pass
                for src, refs in ref_map.items():
                    try:
                        record_reference_edges(conn, normalize_arxiv_id(src), refs)
                    except Exception:
                        pass
        for fentry in sorted(
            unique_foundational.values(),
            key=lambda e: int(e.get("citation_count") or 0),
            reverse=True,
        ):
            if fentry.get("has_pdf") and fentry.get("arxiv_id"):
                try:
                    await _ensure_pdf_cached(fentry, cache_dir)
                    await extract_markdown_from_pdf(
                        fentry,
                        cache_dir=cache_dir,
                        markdown_cache_dir=markdown_cache_dir,
                        db_path=db_path,
                    )
                    fentry["local_pdf_path"] = str(_resolve_pdf_path(fentry, cache_dir))
                except Exception:
                    pass
            try:
                fsummary = await summarize_paper_entry(
                    fentry,
                    cache_dir=cache_dir,
                    summary_cache_dir=summary_cache_dir,
                    markdown_cache_dir=markdown_cache_dir,
                    model=model,
                    variant=variant,
                    prompt_version=prompt_version,
                    refresh=refresh_summaries,
                    db_path=db_path,
                    prompt_kind="foundational",
                )
                foundational_sections.append({"entry": fentry, "summary": fsummary})
                if db_path:
                    _record_enrichment_to_db(
                        db_path,
                        fentry,
                        fsummary,
                        model,
                        variant,
                        prompt_version,
                        "foundational_summary",
                    )
            except Exception:
                foundational_sections.append(
                    {
                        "entry": fentry,
                        "summary": {
                            "results_summary": "Summary unavailable.",
                            "area_of_progress": "",
                            "confidence": "low",
                            "confidence_rationale": "LLM summarization failed.",
                            "primary_claims": [],
                            "required_background": [],
                            "background_research": [],
                            "open_questions": [],
                        },
                    }
                )

    metadata = write_periodical_project(
        periodical_dir=periodical_dir,
        title=title,
        series=series,
        issue=issue,
        manifest=manifest,
        manifest_path=manifest_path,
        manifest_sha256=manifest_sha256,
        sections=sections,
        focus_section=focus_section,
        supporting_sections=supporting_sections,
        category_summaries=category_summaries,
        foundational_sections=foundational_sections,
        ref_map=ref_map,
        model=model,
        variant=variant,
        prompt_version=prompt_version,
        reference_depth=reference_depth,
    )

    periodical_path = Path(periodical_dir)
    dist_dir = periodical_path / ".." / "dist"
    dist_dir.mkdir(parents=True, exist_ok=True)

    build_result = await asyncio.to_thread(
        subprocess.run,
        ["just", "build"],
        cwd=str(periodical_path),
        capture_output=True,
        text=True,
    )
    if build_result.returncode != 0:
        raise RuntimeError(build_result.stderr or build_result.stdout)

    output_pdf = str(dist_dir.resolve() / "research-radar.pdf")
    if db_path and build_id:
        from radar_db import (
            entry_to_paper,
            finish_periodical_build,
            get_db,
            record_periodical_paper,
            upsert_paper,
        )

        with get_db(db_path) as conn:
            for fs in foundational_sections:
                fa_id = str(fs["entry"].get("arxiv_id", ""))
                if fa_id:
                    try:
                        upsert_paper(
                            conn,
                            entry_to_paper(fs["entry"], discovered_via="reference_traversal"),
                        )
                    except Exception:
                        pass
                    record_periodical_paper(conn, build_id, fa_id, "foundational")
            finish_periodical_build(
                conn,
                build_id,
                paper_count=len(sections),
                foundational_count=len(foundational_sections),
                output_pdf=output_pdf,
            )
    return {
        "manifest_path": manifest_path,
        "periodical_dir": str(periodical_path),
        "output_pdf": output_pdf,
        "paper_count": len(sections),
        "foundational_count": len(foundational_sections),
        "model": model,
        "variant": variant,
        "chapter_count": metadata["chapter_count"],
        "series": series,
        "issue": issue,
        "focus": metadata["focus"],
        "summary_index": str(summary_index_path(summary_cache_dir)),
        "build_metadata": str(periodical_path / "build-metadata.json"),
    }
